CREATE TABLE IF NOT EXISTS Projects (
 id INT AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(200) NOT NULL,
 category VARCHAR(100) NOT NULL,
 application_sector VARCHAR(100) NOT NULL,
 description TEXT NOT NULL,
 location_name VARCHAR(200) NOT NULL,
 latitude DECIMAL(10,7) NOT NULL,
 longitude DECIMAL(10,7) NOT NULL,
 image_url VARCHAR(500) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ProjectImages (
 id INT AUTO_INCREMENT PRIMARY KEY,
 project_id INT NOT NULL,
 image_url VARCHAR(500) NOT NULL,
 sort_order INT NOT NULL DEFAULT 0,
 FOREIGN KEY (project_id) REFERENCES Projects(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ProjectProducts (
 project_id INT NOT NULL,
 product_id INT NOT NULL,
 PRIMARY KEY (project_id, product_id),
 FOREIGN KEY (project_id) REFERENCES Projects(id) ON DELETE CASCADE,
 FOREIGN KEY (product_id) REFERENCES Products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ProjectKits (
 project_id INT NOT NULL,
 kit_id INT NOT NULL,
 PRIMARY KEY (project_id, kit_id),
 FOREIGN KEY (project_id) REFERENCES Projects(id) ON DELETE CASCADE,
 FOREIGN KEY (kit_id) REFERENCES Kits(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
